spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://localhost:5432/skillsync_db
spring.datasource.username=postgres
spring.datasource.password=kavya123

jwt.secret=ABWPSBr+wK1tuviHZbPiF3B6DAa4ZOnAI24Hnj7k9xsZJoNW3OezvzlrUST41RGI8G0+otSfyuU2K1MUOLBRnQ==
jwt.expiration=86400000

logging.level.org.springframework.web=DEBUG

gemini.api.key=AIzaSyDxij6d8fB0CjF4erLnmloboUzYim3BbAM

# Caching - reduces rate limiting by caching stats for 30 minutes
spring.cache.type=simple